name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: cocbot-bot-app
  AZURE_WEBAPP_PACKAGE_PATH: 'packages/bot/dist'
  NODE_VERSION: '14.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Yarn Tooling
        run: npm i -g yarn

      - name: Install Dependencies
        run: yarn

      - name: CI Verification
        run: yarn ci

      - name: Prepare Deployment
        run: yarn predeploy:bot

      - name: Install Deployment Modules
        run: pushd packages/bot/dist && npm install && popd
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
